\\vtcfiles1.vtc.vsc.edu\shared\ELM\ELM4701\Bridge Tester\Design\Solidworks Models\Frame REV 2\Main Frame-Study 1
\\vtcfiles1.vtc.vsc.edu\shared\ELM\ELM4701\Bridge Tester\Design\Solidworks Models\Frame REV 2\Main Frame-Puck study
\\vtcfiles1.vtc.vsc.edu\shared\ELM\ELM4701\Bridge Tester\Design\Solidworks Models\Frame REV 2\Main Frame-Puck study
\\vtcfiles1.vtc.vsc.edu\shared\ELM\ELM4701\Bridge Tester\Design\Solidworks Models\Frame REV 2\Main Frame-Test Study
\\vtcfiles1.vtc.vsc.edu\shared\ELM\ELM4701\Bridge Tester\Design\Solidworks Models\Frame REV 2\Main Frame-double point study
